{% set name = "python-neutronclient" %}
{% set version = "10.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-neutronclient-{{ version }}.tar.gz
  sha256: 2926d3dc5af2fc55a1726aa9bb031ec022e475a4b9717cb1f005c67ca4e249f2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pbr >=2.0.0
    - pip
    - python >=3.8
  run:
    - cliff >=3.4.0
    - debtcollector >=1.2.0
    - iso8601 >=0.1.11
    - keystoneauth1 >=3.8.0
    - netaddr >=0.7.18
    - os-client-config >=1.28.0
    - osc-lib >=1.12.0
    - oslo.i18n >=3.15.3
    - oslo.log >=3.36.0
    - oslo.serialization !=2.19.1,>=2.18.0
    - oslo.utils >=3.33.0
    - pbr !=2.1.0,>=2.0.0
    - python >=3.8
    - python-keystoneclient >=3.8.0
    - requests >=2.14.2
    - simplejson >=3.5.1
    - openstacksdk >=1.0.0 # Apache-2.0

test:
  imports:
    - neutronclient
  commands:
    - pip check
    - neutron -h
  requires:
    - pip

about:
  home: https://docs.openstack.org/python-neutronclient/latest/
  summary: CLI and Client Library for OpenStack Networking
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschoonj
